# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               /src/log
tagline:             'Repository of my development experience'
description:         'A blog that talks about my development experience'
url:                 http://srclog.co
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Saurabh Chandolia
  url:               https://twitter.com/pushdlimits
  email:             saurabh@srclog.co

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
